verify_post:
  description: >

    Verify that the given post meets the following criteria:
    
    Criteria
    - it follows the tone of voice instructions to the letter (see below)
    - it is impossible to tell that the post is AI generated
    - it provides value to the reader
    - it contains sources in the form of links to the original research results
    - it contains no emojis
    - It contains only the post itself, without additional commentary
    - It is less than 1500 characters

    Tone of voice instructions:
    {tov_instructions}

    Post:
    {post}

    Additionally, if you believe there are any issues with the post 
    or ways it could be improved, such as the structure of the post,
    rhythm, word choice, please provide feedback.

    If any of the criteria are not met, the post is considered invalid.
    Provide actionable changes about what is wrong and what actions
    need to be taken to fix the post.
    
    Your final response must include:
    - Valid: True/False
    - Feedback: Provide commentary if the post fails any of the criteria.

  expected_output: >
    Pass: True/False
    Feedback: Commentary here if failed.
  agent: post_verifier
